# -*- coding: utf-8 -*-
"""
Merge paired COI amplicons into full-length barcodes using EMBOSS alignment (needle) to generate a consensus sequence.

Inputs:
- renamed_all_HCO2.fasta - all the hco fasta concatenated into a single fasta
- renamed_all_LCO2.fasta - all the lco fasta concatenated into a single fasta
- ALL_OVERLAP.txt - all over the overlaps that were generated by all_pairs in a previous line of code

Outputs:
- Barcode_picks/<i###>_merged.fasta   (consensus merged)
- Combined_amplicons/<i###>_HCO_pick.fasta
- Combined_amplicons/<i###>_LCO_pick.fasta
- Barcode_picks/Seqs_to_barcodes_summary.txt
"""

import os
import shutil
import subprocess
from collections import defaultdict
from Bio import SeqIO, SeqRecord

# --------- Config ---------
HCO_FASTA = "renamed_all_HCO2.fasta"
LCO_FASTA = "renamed_all_LCO2.fasta"
OVERLAP_FILE = "ALL_OVERLAP.txt"

OUT_MERGED_DIR = "Barcode_picks"
OUT_COMBINED_DIR = "Combined_amplicons"
SUMMARY_TSV = os.path.join(OUT_MERGED_DIR, "Seqs_to_barcodes_summary.txt")

MIN_OVERLAP_BP = 85
MIN_IDENTITY = 85.0  # percent
MANUAL_SPACER = "NNNNN"

# --------------------------


def load_fasta_map(path):
    """Return dict: {record.id -> record.seq}"""
    seqs = {}
    with open(path, "r") as fh:
        for rec in SeqIO.parse(fh, "fasta"):
            seqs[rec.id] = rec.seq
    return seqs


def load_overlap_pairs(path):
    """Parse overlap file into {specimen: [(HCO_id, LCO_id, identity, overlap_bp), ...]}"""
    pairs = defaultdict(list)
    with open(path, "r") as fh:
        for line in fh:
            if not line.strip():
                continue
            cols = line.strip().split()
            if len(cols) < 4:
                continue
            hco_id, lco_id = cols[0].strip(), cols[1].strip()
            try:
                identity = float(cols[2])
                ov_len = int(float(cols[3]))
            except Exception:
                continue
            try:
                sid = hco_id.split(".")[1]
            except IndexError:
                continue
            sp_id = sid if sid.startswith("i") else f"i{sid}"
            pairs[sp_id].append((hco_id, lco_id, identity, ov_len))
    return pairs


def pick_best_pair(candidates):
    """Select the best HCO/LCO pair: highest overlap, then highest identity."""
    if not candidates:
        return None
    return sorted(candidates, key=lambda x: (x[3], x[2]), reverse=True)[0]


def ensure_dirs():
    os.makedirs(OUT_MERGED_DIR, exist_ok=True)
    os.makedirs(OUT_COMBINED_DIR, exist_ok=True)


def write_pick_fastas(sp_id, hco_id, lco_id, seqs_HCO, seqs_LCO):
    """Write selected HCO/LCO fragments for record-keeping."""
    hco_seq = SeqRecord.SeqRecord(seqs_HCO[hco_id], id=f"{sp_id}_HCO", description=hco_id)
    lco_seq = SeqRecord.SeqRecord(seqs_LCO[lco_id], id=f"{sp_id}_LCO", description=lco_id)
    SeqIO.write(hco_seq, os.path.join(OUT_COMBINED_DIR, f"{sp_id}_HCO_pick.fasta"), "fasta")
    SeqIO.write(lco_seq, os.path.join(OUT_COMBINED_DIR, f"{sp_id}_LCO_pick.fasta"), "fasta")


def run_emboss_alignment(sp_id):
    """Use EMBOSS needle or merger to align and generate a merged consensus sequence."""
    emboss_tool = shutil.which("needle") or shutil.which("merger")
    if emboss_tool is None:
        print("EMBOSS not found — falling back to manual concatenation.")
        return False, None

    aseq = os.path.join(OUT_COMBINED_DIR, f"{sp_id}_LCO_pick.fasta")
    bseq = os.path.join(OUT_COMBINED_DIR, f"{sp_id}_HCO_pick.fasta")
    align_file = os.path.join(OUT_MERGED_DIR, f"{sp_id}_align.fasta")
    outseq = os.path.join(OUT_MERGED_DIR, f"{sp_id}_merged.fasta")

    cmd = f'{emboss_tool} -asequence "{aseq}" -bsequence "{bseq}" -gapopen 10 -gapextend 0.5 -outfile "{align_file}" -aformat fasta'
    try:
        subprocess.run(cmd, shell=True, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    except subprocess.CalledProcessError as e:
        print(f"EMBOSS failed for {sp_id}: {e}")
        return False, None

    # Parse alignment and merge into consensus
    try:
        from Bio import AlignIO
        alignment = AlignIO.read(align_file, "fasta")

        seq1, seq2 = str(alignment[0].seq), str(alignment[1].seq)
        merged = []
        for b1, b2 in zip(seq1, seq2):
            if b1 == b2:
                merged.append(b1)
            elif b1 == "-":
                merged.append(b2)
            elif b2 == "-":
                merged.append(b1)
            else:
                merged.append("N")  # mismatch → ambiguous

        merged_seq = "".join(merged).replace("-", "")
        from Bio.Seq import Seq
        merged_record = SeqRecord.SeqRecord(Seq(merged_seq), id=sp_id, description="EMBOSS consensus merge")
        SeqIO.write(merged_record, outseq, "fasta")
        return True, align_file

    except Exception as e:
        print(f"Error parsing alignment for {sp_id}: {e}")
        return False, None


def manual_concat(sp_id, hco_id, lco_id, seqs_HCO, seqs_LCO):
    """Concatenate without alignment."""
    outseq = os.path.join(OUT_MERGED_DIR, f"{sp_id}_merged.fasta")
    merged = seqs_LCO[lco_id] + MANUAL_SPACER + seqs_HCO[hco_id]
    SeqIO.write(SeqRecord.SeqRecord(merged, id=sp_id, description="manual_concat_LCO+HCO"), outseq, "fasta")
    return outseq


def main():
    print("Loading FASTAs...")
    seqs_HCO = load_fasta_map(HCO_FASTA)
    seqs_LCO = load_fasta_map(LCO_FASTA)
    print(f"...loaded {len(seqs_HCO)} HCO and {len(seqs_LCO)} LCO sequences.")

    print("Loading overlap pairs...")
    pairs = load_overlap_pairs(OVERLAP_FILE)
    print(f"...loaded overlap info for {len(pairs)} specimens.")

    ensure_dirs()
    merged_ok, merged_manual, skipped = 0, 0, 0

    with open(SUMMARY_TSV, "w") as sf:
        sf.write("Specimen\tHCO_seq\tLCO_seq\tOverlap_bp\tIdentity_pct\tOutcome\n")

        for sp_id, cands in sorted(pairs.items()):
            best = pick_best_pair(cands)
            if best is None:
                sf.write(f"{sp_id}\t\t\t\t\tNo overlap candidates\n")
                skipped += 1
                continue

            hco_id, lco_id, ident, ovlen = best
            if ovlen < MIN_OVERLAP_BP or ident < MIN_IDENTITY:
                sf.write(f"{sp_id}\t{hco_id}\t{lco_id}\t{ovlen}\t{ident:.1f}\tOverlap too weak\n")
                skipped += 1
                continue

            if hco_id not in seqs_HCO or lco_id not in seqs_LCO:
                sf.write(f"{sp_id}\t{hco_id}\t{lco_id}\t{ovlen}\t{ident:.1f}\tMissing sequence(s)\n")
                skipped += 1
                continue

            write_pick_fastas(sp_id, hco_id, lco_id, seqs_HCO, seqs_LCO)

            ok, align_path = run_emboss_alignment(sp_id)
            if ok:
                sf.write(f"{sp_id}\t{hco_id}\t{lco_id}\t{ovlen}\t{ident:.1f}\tAligned+merged (EMBOSS)\n")
                merged_ok += 1
            else:
                manual_concat(sp_id, hco_id, lco_id, seqs_HCO, seqs_LCO)
                sf.write(f"{sp_id}\t{hco_id}\t{lco_id}\t{ovlen}\t{ident:.1f}\tConcatenated (no EMBOSS)\n")
                merged_manual += 1

    print(f"Done. EMBOSS merges: {merged_ok}, manual concats: {merged_manual}, skipped: {skipped}.")
    print(f"Summary file written to: {SUMMARY_TSV}")


if __name__ == "__main__":
    main()
